Home
NovikovaMaria15/weatherWebsite pull request #1
Opened 2022-05-18 15:52 UTC by NovikovaMaria15

2022-05-19 05:33 UTC, retoko requested changes

2022-05-19 05:33 UTC, retoko commented on README.md
> +# Getting Started with Create React App
Это файл-инструкция к репозиторию, тут можно написать что это за сайт, как его использовать, как запускать

2022-05-19 05:33 UTC, retoko commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
почитай зачем нужен этот файл для общего развития

2022-05-19 05:33 UTC, retoko commented on src/App.test.js
> +test('renders learn react link', () => {
это тесты, ты пробовала их запускать? надо понять как они работают, чтобы в дальнейшем научиться тестировать свой код. на текущий момент предлагаю научиться запускать один этот тест и если он не проходит починить его.

2022-05-19 05:33 UTC, retoko commented on src/App.tsx
> +    <div className="App">
зачем тут этот div?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/Home.tsx
> +import { useAppDispatch, RootState } from '../../store/store';
импорты, которые лежат далеко от это страницы, лучше импортировать по абсолютной ссылке
```suggestion
import { useAppDispatch, RootState } from 'src/store/store';
```

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/Home.tsx
> +  const [city1, setCity] = useState('');
что такое city1? почему 1. а не 2?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/Home.tsx
> +  const [open, setOpen] = useState(false);
open что? дверь?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/Home.tsx
> +  const anyCity = useCallback(() => {
useCallback нет смысла использовать в этом компоненте, почитай когда надо его использовать и убери их тут

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/Home.tsx
> +    anyCity();
1. зачем тут 2 функции anyCity и anyCity1? кажется они вообще одинаковые...
2. что такое anyCity? Такое ощущение что функция загружает информацию о погоде - loadWeatherInformation 
3. что такое setOpen? Тебе вообще нужен этот Стейт? может просто надо проверять есть ли у тебя данные о погоде и если есть - отображать?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
а если экран будет другого размера иконка уедет?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/HomeStyles.js
> +  height: 400px;
нижнее свойство переопределяет верхнее, оставь что-то одно

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
тот же вопрос, инпут уедет на другом экране?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
и тут тоже. ты вообще понимаешь как работает position absolute? может не надо его использовать?

2022-05-19 05:33 UTC, retoko commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
и тут

2022-05-19 05:33 UTC, retoko commented on src/pages/components/Current/Current.tsx
> +export function Current({ dayCurrent }: any) {
Нет смысла выносить это в отдельный компонент, в нем ничего нету

2022-05-19 05:33 UTC, retoko commented on src/pages/components/EndPage/EndPage.jsx
> +    <S.HeaderWeather>
Зачем тут 3 вложенных друг в друга стиля? тут точно нет лишних? Может что-то можно убрать?

2022-05-19 05:33 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +  // const [dayDay, alignmentDayDay] = useState(false);
комментарии надо убрать

2022-05-19 05:33 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +      {' '}
что это?

2022-05-19 05:33 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +export function HourlyDay() {
этот компонент вообще нужен? тут одни комментарии
если то что-то не доделала - не надо коммитить ненужные файлы.
надо научиться работать с git flow
сделала фичу, создала PR
потом создала отдельную ветку - и в ней делаешь другую фичу
у тебя получается каша потому что все в одном PR

2022-05-19 05:33 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +        console.log('dt', dt);
консоль логи надо убирать после того как закончишь отладку

2022-05-19 05:33 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +      setOpen(false);
что такое setOpen и зачем он нужен?

2022-05-19 05:33 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +    <>
тут надо разбить на компоненты

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/Home.tsx
> +import { useAppDispatch, RootState } from '../../store/store';
Cannot find module 'src/store/store' or its corresponding type declarations.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/Home.tsx
> +  const [open, setOpen] = useState(false);
открыть

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/Home.tsx
> +  const anyCity = useCallback(() => {
не должно быть перерендеров, когда city1 обновляется, тогда и обновляется эта функция.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/Home.tsx
> +    anyCity();
Одна вызывается userWeather, а другая weekWeather. anyCity - любой город. С помощью opena показывается погода. Она выходит не сразу.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
Нет.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
Нет.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/Home/HomeStyles.js
> +  position: absolute;
Да, понимаю. 
Если у тебя есть другое предложение, как можно инут разместить поверх картинки, буду рада послушать.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/components/Current/Current.tsx
> +export function Current({ dayCurrent }: any) {
Там заголовок. Я посчитала, что можно вынести.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +export function HourlyDay() {
Я ещё не дошла до такого уровня сокращений. Что такое PR?

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +      {' '}
Над этим файлом я начала работать.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/components/WeekDay/WeekDay.tsx
> +      setOpen(false);
Выводит информацию когда нужно и убирает когда она уже не нужна.

2022-05-21 16:22 UTC, NovikovaMaria15 commented on src/pages/components/WeekDay/WeekDay.tsx
> +    <>
Что конкретно?

2022-05-21 16:22 UTC, NovikovaMaria15 commented on README.md
> +# Getting Started with Create React App
Так там написано уже как его запускать...

2022-05-21 16:37 UTC, retoko requested changes

2022-05-21 16:37 UTC, retoko commented on src/pages/components/EndPage/EndPage.jsx
> +export function EndPage() {
Это называется Footer

2022-05-21 16:37 UTC, retoko commented on src/pages/components/EndPage/EndPageStyles.js
> +// export const CenterAlignment = styled.div`
удалить

2022-05-21 16:37 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +  const HourlyDayy = dayHourly.find((week: any) => {
с маленькой буквы назвать

2022-05-21 16:37 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +  const Hourly = HourlyDayy;
это зачем?

2022-05-21 16:37 UTC, retoko commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +        temp={Math.round(Hourly.temp - 273)}
надо создать функцию по переводу температуры в градусы Цельсия, вынести в отдельный файл и использовать везде

2022-05-21 16:37 UTC, retoko commented on src/pages/components/WeatherItemsStyles.js
> +export const Text = styled.div`
удалить

2022-05-21 16:37 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +  // const [dayDay, alignmentDayDay] = useState(false);
удалить

2022-05-21 16:37 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +    <>
как минимум то что у тебя пробелами разделено можно на 3 компонента разбить

2022-05-21 16:37 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +      setOpen(false);
нужно назвать нормально

2022-05-21 16:37 UTC, retoko commented on src/pages/weekComponents/WeatherDay/WeatherDay.tsx
> +export function WeatherDay({ dayy }: any) {
бесполезный компонент, удалить

2022-05-21 16:40 UTC, retoko commented on src/pages/Home/Home.tsx
> +import { useAppDispatch, RootState } from '../../store/store';
ну сделай правильно, чтобы нашелся

2022-05-21 16:40 UTC, retoko commented on src/pages/Home/Home.tsx
> +  const [city1, setCity] = useState('');
надо нормально назвать

2022-05-21 16:40 UTC, retoko commented on src/pages/Home/Home.tsx
> +  const [open, setOpen] = useState(false);
надо нормально назвать

2022-05-21 16:41 UTC, retoko commented on src/pages/Home/Home.tsx
> +    anyCity();
надо нормально назвать

2022-05-21 16:41 UTC, retoko commented on src/pages/components/Current/Current.tsx
> +export function Current({ dayCurrent }: any) {
не нужно, стайл компонент и так как отдельный компонент

2022-05-21 17:22 UTC, NovikovaMaria15 commented on src/pages/components/WeekDay/WeekDay.tsx
> +    <>
Нельзя, там они все связаны друг с другом через withdraw.

2022-05-21 17:27 UTC, NovikovaMaria15 commented on src/pages/components/HourlyDay/HourlyDay.tsx
> +  const Hourly = HourlyDayy;
В смысле зачем? Чтобы вывести find в return.

2022-05-21 18:36 UTC, retoko requested changes

2022-05-21 18:36 UTC, retoko commented on src/pages/components/WeekDay/WeekDay.tsx
> +  const [dayDayDay, setDayDayDay]: any[] = useState('');
daydayday надо назвать нормально

2022-05-21 18:36 UTC, retoko commented on src/store/weekWeather/weekWeatherThunk.tsx
> +      const responsee = await axios.get(
назвать нормально

2022-06-07 14:33 UTC, merged